"""Export env diffs and merged envs to various output formats."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, Optional

from envdiff.redactor import redact_env_dict


def export_env_dict_to_dotenv(
    env: Dict[str, str],
    output_path: str,
    redact: bool = False,
    header_comment: Optional[str] = None,
) -> None:
    """Write an env dict to a .env file.

    Args:
        env: Mapping of key -> value to write.
        output_path: Destination file path.
        redact: If True, sensitive values are replaced with a placeholder.
        header_comment: Optional comment line written at the top of the file.
    """
    data = redact_env_dict(env) if redact else env
    lines = []
    if header_comment:
        for line in header_comment.splitlines():
            lines.append(f"# {line}\n")
        lines.append("\n")
    for key, value in sorted(data.items()):
        # Quote values that contain spaces or special shell characters.
        if any(ch in value for ch in (" ", "\t", "#", "$", "\"", "'")):
            escaped = value.replace('"', '\\"')
            lines.append(f'{key}="{escaped}"\n')
        else:
            lines.append(f"{key}={value}\n")
    Path(output_path).write_text("".join(lines), encoding="utf-8")


def export_env_dict_to_json(
    env: Dict[str, str],
    output_path: str,
    redact: bool = False,
    indent: int = 2,
) -> None:
    """Write an env dict to a JSON file.

    Args:
        env: Mapping of key -> value to write.
        output_path: Destination file path.
        redact: If True, sensitive values are replaced with a placeholder.
        indent: JSON indentation level.
    """
    data = redact_env_dict(env) if redact else env
    Path(output_path).write_text(
        json.dumps(data, indent=indent, sort_keys=True), encoding="utf-8"
    )


def export_env_dict_to_shell(
    env: Dict[str, str],
    output_path: str,
    redact: bool = False,
) -> None:
    """Write an env dict as a shell export script.

    Args:
        env: Mapping of key -> value to write.
        output_path: Destination file path.
        redact: If True, sensitive values are replaced with a placeholder.
    """
    data = redact_env_dict(env) if redact else env
    lines = ["#!/usr/bin/env sh\n", "# Generated by envdiff\n", "\n"]
    for key, value in sorted(data.items()):
        escaped = value.replace("'", "'\"'\"'")
        lines.append(f"export {key}='{escaped}'\n")
    Path(output_path).write_text("".join(lines), encoding="utf-8")
